version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "jasmine",
    "jquery",
    "cypress",
    "mongo"
  ]